### ISSUE TITLE
Recent changes backported to SS3

### ISSUE THREAD

**Issue by PortableSteve** [stevie-mayhew/hasoneedit#14]
I have backported all the recent changes that have been committed to the master branch to work with the SS3 branch here: https://github.com/PortableSteve/hasoneedit/tree/merge-ss4-changes

This includes support for `UploadField`s, the `HasOneEdit` class and the `ProvidesHasOneInlineFields` trait.

Is this something you are interested in incorporating back into the main repository? Do you want a PR for this?

**Comment by stevie-mayhew** [comment]
Sounds like a good idea, I'd be happy to incorporate them! Want to do a PR against the 3.x branch?

**Comment by PortableSteve** [comment]
Done: #15

**Comment by stevie-mayhew** [comment]
Merged :) I hope this works ;)
