### ISSUE TITLE
Doesn't work on latest SS4?

### ISSUE THREAD

**Issue by dmcb** [stevie-mayhew/hasoneedit#16]
When viewing the admin area of an owner object using HasOneEdit on a data object, where that data object is using the ProvidesHasOneInlineFields trait to return CMS fields, I get the following error:

```
[Emergency] Uncaught Error: Call to a member function getName() on array
Line 278 in /var/www/html/vendor/silverstripe/framework/src/Forms/FieldList.php
```

I'm not doing anything wrong that I can tell from the documentation.

**Comment by stevie-mayhew** [comment]
Hey @dmcb - would you be able to diagnose this a bit further and potentially do a PR with a change which makes this work? I'm not actively working on this repository but am open to merging new code if you can help do it!

**Comment by GuySartorelli** [comment]
@dmcb What version of framework was that, do you remember?

**Comment by GuySartorelli** [comment]
As an update, I've just tried this in 4.9.1 and it's working fine for me - I think this can be closed.

**Comment by stevie-mayhew** [comment]
Awesome :)
