### ISSUE TITLE
Error using HasOneEdit::getInlineFields

### ISSUE THREAD

**Issue by polycode-nz** [stevie-mayhew/hasoneedit#17]
SilverStripe 4.5.

Doing what the docs say in one line like this:

`
$fields->addFieldToTab('Root.Fees', HasOneEdit::getInlineFields($this, 'Fees'));
`

results in:

> [Emergency] Uncaught TypeError: Argument 1 passed to SilverStripe\Forms\CompositeField::push() must be an instance of SilverStripe\Forms\FormField, array given, called in /var/www/html/vendor/silverstripe/framework/src/Forms/FieldList.php on line 249

Changing to:

```
$FeeFields = HasOneEdit::getInlineFields($this, 'Fees');

foreach ($FeeFields as $field)
{
    $fields->addFieldToTab('Root.Fees', $field);
}

```

Works fine.

**Comment by stevie-mayhew** [comment]
Looks like "Fees" is an array of many fields, not a single field?

**Comment by polycode-nz** [comment]
@stevie-mayhew yeah, it's all it's fields as the name suggests getInlineField**s**()

**Comment by stevie-mayhew** [comment]
Would be happy for a PR as I'm not currently looking to put work into this module, but happy to merge if you get something done!

**Comment by polycode-nz** [comment]
@stevie-mayhew Mm, I don't think it's an issue/bug with the code. Everything there points to it returning an array of fields. Basic update to the docs should do it.

**Comment by michalkleiner** [comment]
@polycode-nz the readme is correct, there are two methods for adding fields to CMS fields, one accepting a single field (`addFieldToTab` — note singular) and one accepting an array of fields (used correctly in the docs and the one you should use — `addFieldsToTab` — note plural).

**Comment by polycode-nz** [comment]
@michalkleiner yup, you got me there.
