### ISSUE TITLE
Possible to get working on SiteConfig?

### ISSUE THREAD

**Issue by lars-lemon8** [stevie-mayhew/hasoneedit#26]
We are dealing with a very bloated SiteConfig (the DB table is getting too wide, lol).  So I'm considering moving some of the siteconfig data to a separate data-object.  This module seems perfect, but I'm having a little issue with getting the fields populated.

The method updateEditForm needs the $form object to be passed, but I can't seem to obtain that (the $form object) from with the site config extension. 

Does anyone know of a trick to get this working on the siteconfig ?

**Comment by xini** [comment]
I would have thought this works out of the box... hmm..

(The form object is injected by the extension hooks in https://github.com/silverstripe/silverstripe-framework/blob/5/src/Forms/GridField/GridFieldDetailForm_ItemRequest.php#L307 and https://github.com/silverstripe/silverstripe-cms/blob/5/code/Controllers/CMSMain.php#L1393. Have a look at how extensions work and pass on variables in SS on https://docs.silverstripe.org/en/5/developer_guides/extending/extensions/#modifying-existing-methods.)

Can you try to add the following config to your app's yml config? Maybe the extension is not being applied to the siteconfig's `CMSMain` subclass and needs to be added manually. If this works, we can submit a PR to the module to add this config.
(I haven't tried this snippet myself, it's just a guess... ;) )

```
---
Name: app-hasoneedit
After: 'hasoneedit'
Only:
  moduleexists: 'silverstripe/siteconfig'
---
SilverStripe\SiteConfig\SiteConfigLeftAndMain:
  extensions:
    - SGN\HasOneEdit\UpdateFormExtension
```

**Comment by lars-lemon8** [comment]
Hi Florian,

Thank you very much !! That did the trick.
Makes sense now I look at it.  The left and main is responsible for the form itself, right?

**Comment by xini** [comment]
Hi Lars,

I have created a pull request (https://github.com/stevie-mayhew/hasoneedit/pull/27) to add that config to the module.

`LeftAndMain` is the main back-end controller for the admin. It has two subclasses, `CMSMain` for pages and `SiteConfigLeftAndMain` for the siteconfig (plus some more for other things). The forms are loaded through these controllers' `getEditForm()` method, the form fields are loaded via the `getCMSFields()` method of the edited `DataObject` (here `SiteConfig`).
